accounts/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name ='accounts/logout.html'), name ='logout'),
    path('edit/', views.editProfile, name='editProfile'),
    path('change-password/', views.changePass, name='changePass'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

evolves/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('shop/', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('product/<int:id>/<url>/', views.prodView, name='prodView'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Address
from django.db.models.signals import post_save

# Create your models here.

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	phone = models.PositiveSmallIntegerField(max_length=10)
	dob = models.DateField(null=True, blank=True)
	gender = models.CharField(default='', max_length=50, blank=True)
	default_address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='default_address', blank=True, default=1)

	def __str__(self):
		return self.user.username

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
	first_name = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'First Name', 'autocomplete':'off', 'autofocus':'on'}))
	last_name = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Last Name', 'autocomplete':'off'}))
	username = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Username', 'autocomplete':'off'}))
	email = forms.EmailField(label='', widget=forms.EmailInput(attrs={'placeholder':'Email', 'autocomplete':'off'}))
	password1 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
	password2 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))



class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    username = forms.CharField(widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    password = None




class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone','gender']

    phone = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'col-5'}))
    gender = forms.ChoiceField(required=False, choices=[('female', 'Female'), ('male', 'Male')], widget=forms.RadioSelect())

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm, EditProfileForm, UserProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


def index(request):
	return render(request, 'accounts/index.html')


def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			form = RegistrationForm()
			messages.success(request, 'New user created successfully.')
			return redirect('/accounts/login')
	else:
		form = RegistrationForm()

	context = {'form': form}
	return render(request, 'accounts/register.html', context)


# def login(request):
#     return render(request, 'accounts/login.html')

@login_required
def editProfile(request):
	if request.method == 'POST':
		edituser_form = EditProfileForm(request.POST, instance=request.user)
		editprofile_form = UserProfileForm(request.POST, instance=request.user.userprofile)

		if edituser_form.is_valid() and editprofile_form.is_valid():
			edituser_form.save()
			editprofile_form.save()
			return redirect('/accounts')
	else:
		edituser_form = EditProfileForm(instance=request.user)
		editprofile_form = UserProfileForm(instance=request.user.userprofile)

	context = {'edituser_form': edituser_form, 'editprofile_form': editprofile_form}
	return render(request, 'accounts/edit-profile.html', context)


@login_required
def changePass(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)

		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect('/accounts/edit')
	else:
		form = PasswordChangeForm(user=request.user)
	context = {'form': form}
	return render(request, 'accounts/change-password.html', context)

accounts/templates/accounts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %} • Evolves</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'accounts/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'accounts/css/style.css?random=450' %}">
</head>
<body>

	{% if messages %}
	<ul class="messages text-center h4">
		{% for message in messages %}
		<div class="alert alert-dark alert-dismissible fade show" role="alert">
		{{ message }}
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		</div>
		{% endfor %}
	</ul>
	{% endif %}

    <div class="main">

        {% block body %}{% endblock body %}

    </div>

    <!-- JS -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'accounts/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'accounts/js/main.js?random=34' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

accounts/templates/accounts/change-password.html
{% extends 'shop/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Change Password • Evolves{% endblock title %}

{% block body %}

<div class="container my-5">
<img src="{% static 'shop/img/change-password.png' %}" class="editPageImg img-responsive float-right" height="400px" onContextMenu="return false;" draggable="false" alt="...">
    
    <div class="col-lg-6">
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="site-btn">Save</button>
        </form>
    </div>
</div>
<br><br><br><br><br>

{% endblock body %}

accounts/templates/accounts/edit-profile.html
{% extends 'shop/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Edit Account Details • Evolves{% endblock title %}

{% block body %}


<div class="container my-5">    
<img src="{% static 'shop/img/man-using-laptop.png' %}" class="editPageImg img-responsive float-right" height="477px" onContextMenu="return false;" draggable="false" style alt="...">
    <div class="col-lg-6">
        <form method="POST">
            {% csrf_token %}
            {{edituser_form|crispy}}
            {{editprofile_form|crispy}}
            <button type="submit" class="site-btn my-2">Save</button>
        </form>
    <p class="changePassNavPara font-italic">To change password click <a href="{% url 'accounts:changePass' %}">here</a>.</p>
    </div>
</div>

{% endblock body %}

accounts/templates/accounts/index.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Your Account • Evolves{% endblock title %}

{% block body %}

<div class="container my-5">
<style>
img{
    user-select: none;
}
.account:hover{
    background-color: #ffbbcf24;
}
</style>
    <div class="row my-5">
        <div class="account card mx-4 p-2" style="max-width: 340px; cursor:pointer;">
            <div class="row no-gutters">
                <div class="col-md-4 my-auto">
                    <img src="{% static 'accounts/images/order.png' %}" class="card-img" alt="..." onContextMenu="return false;" draggable="false">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Your Orders</h5>
                        <p class="card-text">Track, return and buy things again.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="account card mx-4 p-2" style="max-width: 340px; cursor:pointer;">
            <div class="row no-gutters">
                <div class="col-md-4 my-auto">
                    <img src="{% static 'accounts/images/sign-in-lock.png' %}" class="card-img" alt="..." onContextMenu="return false;" draggable="false">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Login and Security</h5>
                        <p class="card-text">Edit login, name, mobile number.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="account card mx-4 p-2" style="max-width: 340px; cursor:pointer;">
            <div class="row no-gutters">
                <div class="col-md-4 my-auto">
                    <img src="{% static 'accounts/images/address.png' %}" class="card-img" alt="..." onContextMenu="return false;" draggable="false">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Your Addresses</h5>
                        <p class="card-text">Edit addresses for orders and gift.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="row my-5">
        <div class="account card mx-4 p-2" style="max-width: 340px; cursor:pointer;">
            <div class="row no-gutters">
                <div class="col-md-4 my-auto">
                    <img src="{% static 'accounts/images/digital.png' %}" class="card-img" alt="..." onContextMenu="return false;" draggable="false">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Digital contents and devices</h5>
                        <p class="card-text">Apps, content, devices and more.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="account card mx-4 p-2" style="max-width: 340px; cursor:pointer;">
            <div class="row no-gutters">
                <div class="col-md-4 mt-3">
                    <img src="{% static 'accounts/images/privacy.png' %}" class="card-img" alt="..." onContextMenu="return false;" draggable="false">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Privacy Policy</h5>
                        <p class="card-text">See all our Policies and T&Cs.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="account card mx-4 p-2" style="max-width: 340px; cursor:pointer;">
            <div class="row no-gutters">
                <div class="col-md-4 mt-3">
                    <img src="{% static 'accounts/images/feedback.png' %}" class="card-img" alt="..." onContextMenu="return false;" draggable="false">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Feedback</h5>
                        <p class="card-text">Submit a report regarding our service.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block body %}

<!-- Sing in  Form -->
<section class="sign-in">
	<div class="container">
		<div class="signin-content">
			<div class="signin-image">
				<figure><img src="{% static 'accounts/images/signin-image.jpg' %}" onContextMenu="return false;" draggable="false" alt="sing up image"></figure>
				<a href="{% url 'accounts:register' %}" class="signup-image-link">Create an account</a>
			</div>

			<div class="signin-form">
				<h2 class="form-title">Login</h2>
				<form method="POST" class="register-form" id="login-form">
				{% csrf_token %}
				{{form|crispy}}
					<div class="form-group">
						<input type="checkbox" name="remember-me" id="remember-me" class="agree-term" checked>
						<label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
					</div>
					<div class="form-group form-button">
						<input type="submit" name="signin" id="signin" class="form-submit" value="Log in">
					</div>
				</form>
				<div class="social-login">
					<span class="social-label">Or login with</span>
					<ul class="socials">
						<li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
						<li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
						<li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock body %}

accounts/templates/accounts/logout.html
<script>window.location="{% url 'accounts:login' %}"</script>

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Create Account{% endblock title %}

{% block body %}
<!-- Sign up form -->
<section class="signup">
	<div class="container">
		<div class="signup-content">
			<div class="signup-form">
				<h2 class="form-title">Sign up</h2>
				<form method="POST" class="register-form" id="register-form">
				{% csrf_token %}
				{{form|crispy}}
					<div class="form-group">
						<input type="checkbox" name="agree-term" id="agree-term" class="agree-term"/>
						<label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a>
					</div>
					<div class="form-group form-button">
						<input type="submit" name="signup" id="signup" class="form-submit" value="Register">
					</div>
				</form>
			</div>
			<div class="signup-image">
				<figure><img src="{% static 'accounts/images/signup-image.jpg' %}" onContextMenu="return false;" draggable="false" alt="sing up image"></figure>
				<a href="{% url 'accounts:login' %}" class="signup-image-link">I am already member</a>
			</div>
		</div>
	</div>
</section>

{% endblock body %}